/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Generics;

import Control.Aeronaves;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class App {
    

    public static void main(String[] args) {
        Scanner leia = new Scanner(System.in);
            
        ///Objeto String da classe aeronave.
        Aeronaves<String> air = new Aeronaves<>();
        
        ///informa o número de aeronaves
        System.out.println("Informe o numero de aeronaves");
        int nrAeronaves = leia.nextInt();
        
        ///Adicionando voos
        for (int i = 0 ; i < nrAeronaves; i++){
            String nrVoo = JOptionPane.showInputDialog("Informe o n° do voo");
            air.addVoo(nrVoo);
        }
        ///retorna o primeiro voo
        air.primeiroVoo();
        
        ///atribuimos o primeiro voo a uma variavel
        String x = air.primeiroVoo();
        
        ///usamos ela para imprimir o valor na tela.
        System.out.println("O primeiro a decolar é o voo: " + x);
        
        ///chama o método que faz a lista de voos
        air.listaVoos();
        leia.close();
    }
}
